### ISSUE TITLE
hello_world doesn't build in linux with reccomended setup

### ISSUE THREAD

**Issue by misaim** [QuantumBadger/Speedy2D#99]
G'day all,

For reference I'm on latest ubuntu. Tried to run the hello_world example - first by copying it into a blank project with required dependencies (Speedy2D 1.12.0 and log/simple_logger. Error message:

```error[E0308]: mismatched types
  --> src/main.rs:37:40
   |
37 |      window.run_loop(MyWindowHandler { text })
   |                                        ^^^^ expected `FormattedTextBlock`, found `Rc<FormattedTextBlock>`
   |
   = note: expected struct `FormattedTextBlock`
              found struct `Rc<FormattedTextBlock>`

error[E0308]: mismatched types
   --> src/main.rs:53:58
    |
53  |          graphics.draw_text((290.0, 90.0), Color::BLACK, &self.text);
    |                   ---------                              ^^^^^^^^^^ expected `&Rc<FormattedTextBlock>`, found `&FormattedTextBlock`
    |                   |
    |                   arguments to this method are incorrect
    |
    = note: expected reference `&Rc<FormattedTextBlock>`
               found reference `&FormattedTextBlock`
note: method defined here
   --> ~./.cargo/registry/src/index.crates.io-6f17d22bba15001f/speedy2d-1.12.0/src/lib.rs:796:12
    |
796 |     pub fn draw_text<V: Into<Vec2>>(
    |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
```

I tried cloning this repo and running it with `cargo run --example hello_world` and it worked, to my surprise. 

So I tried copying dep versions from Speedy2D cargo.toml to my blank project but the error persists. 

For the life of me, I can't figure out the difference: Any suggestions?

**Comment by QuantumBadger** [comment]
Thanks for the report! This is because the current examples in `master` are designed to work with v2.0.0, which hasn't been released yet.

I'm hoping to release v2.0.0 soon. In the meantime, please use the examples from the previous release:

https://github.com/QuantumBadger/Speedy2D/tree/a00cd814ae6081cd09cb1e591ee06ec5d0b28261/examples

**Comment by misaim** [comment]
Welcome! 

Cloned locally and and confirm problem solved. I'll keep using bleeding edge :) 

I'm testing a couple libraries for a combined web / desktop rendering. This and bevy seem to fill the niche well, although bevy's raw graphics API leaves a lot to be desired, plus builds can be large.

**Comment by QuantumBadger** [comment]
Version 2.0.0 now released :)
